name: Destroy Infrastructure

on:
  workflow_dispatch:   # Allows manual trigger from GitHub UI
  # Or use:
  # push:
  #   branches:
  #     - destroy

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      TF_WORKING_DIR: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  # use your version

      - name: Initialize Terraform
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -var "image_uri=108782093329.dkr.ecr.us-east-1.amazonaws.com/onlinebookstore:latest"
